/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bil481_App;
import java.util.ArrayList;

public class App {
    public boolean isNumbersInArrayList(ArrayList<Integer> list, int num1, int num2){
        if(list == null){
            return false;
        }

        if(list.size() <= 1){
            return false;
        }

        for(int check1 : list){
            if(check1 == num1){
                for(int check2 : list){
                    if(check2 == num2){
                        return true;
                    }
                }
            }
        }

        return false;
    }

    public static void main(String[] args) {
        
    }
}
